apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ridwan157@outlook.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones:
            - ridwanahmed.com          # the parent zone, not labs.ridwanahmed.com
        dns01:
          route53:
            region: eu-west-2
            hostedZoneID: Z0717143R661NCU61KOX
      - http01:
          ingress:
            class: nginx
